require 'Items/ProceduralDistributions'

-- Magazines: Tactical Granny Mag vol 1
table.insert(ProceduralDistributions.list["BinBar"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["BinBar"].items, 0.25)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.25)
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5)
table.insert(ProceduralDistributions.list["BreakRoomShelves"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["BreakRoomShelves"].items, 0.25)
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, 0.5)
table.insert(ProceduralDistributions.list["CarWindows1"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CarWindows1"].items,0.25)
table.insert(ProceduralDistributions.list["CarWindows2"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CarWindows2"].items,0.25)
table.insert(ProceduralDistributions.list["CarWindows3"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CarWindows3"].items,0.25)
table.insert(ProceduralDistributions.list["CrateBooks"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.25)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 0.25)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.25)
table.insert(ProceduralDistributions.list["CrateTools"].junk.items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["CrateTools"].junk.items, 0.25)
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 0.5)
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, 0.5)
table.insert(ProceduralDistributions.list["GarageMechanics"].junk.items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["GarageMechanics"].junk.items, 0.25)
table.insert(ProceduralDistributions.list["LibraryBooks"].junk.items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["LibraryBooks"].junk.items, 0.25)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.25)
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.5)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5)
table.insert(ProceduralDistributions.list["OfficeDesk"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["OfficeDesk"].items, 0.25)
table.insert(ProceduralDistributions.list["OtherGeneric"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["OtherGeneric"].items, 0.25)
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 0.25)
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items,0.25)
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, 0.25)
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.25)
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.25)
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "TaticalGrannyMag1")
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 0.25)


-- Magazines: Kentucky Appalachian Cooking Magazine Vol. 1
table.insert(ProceduralDistributions.list["BinBar"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["BinBar"].items, 0.25)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.25)
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5)
table.insert(ProceduralDistributions.list["BreakRoomShelves"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["BreakRoomShelves"].items, 0.25)
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CarSupplyTools"].items, 0.5)
table.insert(ProceduralDistributions.list["CarWindows1"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CarWindows1"].items,0.25)
table.insert(ProceduralDistributions.list["CarWindows2"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CarWindows2"].items,0.25)
table.insert(ProceduralDistributions.list["CarWindows3"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CarWindows3"].items,0.25)
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.25)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 0.25)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.25)
table.insert(ProceduralDistributions.list["CrateTools"].junk.items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["CrateTools"].junk.items, 0.25)
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 0.5)
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, 0.5)
table.insert(ProceduralDistributions.list["GarageMechanics"].junk.items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["GarageMechanics"].junk.items, 0.25)
table.insert(ProceduralDistributions.list["LibraryBooks"].junk.items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["LibraryBooks"].junk.items, 0.25)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.25)
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.5)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5)
table.insert(ProceduralDistributions.list["OfficeDesk"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["OfficeDesk"].items, 0.25)
table.insert(ProceduralDistributions.list["OtherGeneric"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["OtherGeneric"].items, 0.25)
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 0.25)
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items,0.25)
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, 0.25)
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.25)
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["StoreShelfMechanics"].items, 0.25)
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "KentuckyAppalachianCookingMag1")
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 0.25)